import { ContextState, PeriodicWaveConstraints, OfflineAudioContextOptions, AudioBufferBaseSourceNodeOptions, IIRFilterNodeOptions } from '../types';
import BaseAudioContext from './BaseAudioContext';
import AnalyserNode from './AnalyserNode';
import AudioDestinationNode from './AudioDestinationNode';
import AudioBuffer from './AudioBuffer';
import AudioBufferSourceNode from './AudioBufferSourceNode';
import BiquadFilterNode from './BiquadFilterNode';
import IIRFilterNode from './IIRFilterNode';
import GainNode from './GainNode';
import OscillatorNode from './OscillatorNode';
import PeriodicWave from './PeriodicWave';
import StereoPannerNode from './StereoPannerNode';
import ConstantSourceNode from './ConstantSourceNode';
import WaveShaperNode from './WaveShaperNode';
import ConvolverNode from './ConvolverNode';
import { ConvolverNodeOptions } from './ConvolverNodeOptions';
import DelayNode from './DelayNode';
export default class OfflineAudioContext implements BaseAudioContext {
    readonly context: globalThis.OfflineAudioContext;
    readonly destination: AudioDestinationNode;
    readonly sampleRate: number;
    constructor(options: OfflineAudioContextOptions);
    constructor(numberOfChannels: number, length: number, sampleRate: number);
    get currentTime(): number;
    get state(): ContextState;
    createOscillator(): OscillatorNode;
    createConstantSource(): ConstantSourceNode;
    createGain(): GainNode;
    createDelay(maxDelayTime?: number): DelayNode;
    createStereoPanner(): StereoPannerNode;
    createBiquadFilter(): BiquadFilterNode;
    createIIRFilter(options: IIRFilterNodeOptions): IIRFilterNode;
    createConvolver(options?: ConvolverNodeOptions): ConvolverNode;
    createBufferSource(options?: AudioBufferBaseSourceNodeOptions): Promise<AudioBufferSourceNode>;
    createBuffer(numOfChannels: number, length: number, sampleRate: number): AudioBuffer;
    createPeriodicWave(real: Float32Array, imag: Float32Array, constraints?: PeriodicWaveConstraints): PeriodicWave;
    createAnalyser(): AnalyserNode;
    createWaveShaper(): WaveShaperNode;
    decodeAudioDataSource(source: string): Promise<AudioBuffer>;
    decodeAudioData(arrayBuffer: ArrayBuffer): Promise<AudioBuffer>;
    startRendering(): Promise<AudioBuffer>;
    resume(): Promise<void>;
    suspend(suspendTime: number): Promise<void>;
}
//# sourceMappingURL=OfflineAudioContext.d.ts.map