import { IBaseAudioContext } from '../interfaces';
import { AudioBufferBaseSourceNodeOptions, AudioWorkletRuntime, ContextState, ConvolverNodeOptions, DecodeDataInput, IIRFilterNodeOptions, PeriodicWaveConstraints } from '../types';
import AnalyserNode from './AnalyserNode';
import AudioBuffer from './AudioBuffer';
import AudioBufferQueueSourceNode from './AudioBufferQueueSourceNode';
import AudioBufferSourceNode from './AudioBufferSourceNode';
import AudioDestinationNode from './AudioDestinationNode';
import BiquadFilterNode from './BiquadFilterNode';
import ConstantSourceNode from './ConstantSourceNode';
import ConvolverNode from './ConvolverNode';
import DelayNode from './DelayNode';
import GainNode from './GainNode';
import IIRFilterNode from './IIRFilterNode';
import OscillatorNode from './OscillatorNode';
import PeriodicWave from './PeriodicWave';
import RecorderAdapterNode from './RecorderAdapterNode';
import StereoPannerNode from './StereoPannerNode';
import StreamerNode from './StreamerNode';
import WaveShaperNode from './WaveShaperNode';
import WorkletNode from './WorkletNode';
import WorkletProcessingNode from './WorkletProcessingNode';
import WorkletSourceNode from './WorkletSourceNode';
export default class BaseAudioContext {
    readonly destination: AudioDestinationNode;
    readonly sampleRate: number;
    readonly context: IBaseAudioContext;
    constructor(context: IBaseAudioContext);
    get currentTime(): number;
    get state(): ContextState;
    decodeAudioData(input: DecodeDataInput, fetchOptions?: RequestInit): Promise<AudioBuffer>;
    decodePCMInBase64(base64String: string, inputSampleRate: number, inputChannelCount: number, isInterleaved?: boolean): Promise<AudioBuffer>;
    createWorkletNode(callback: (audioData: Array<Float32Array>, channelCount: number) => void, bufferLength: number, inputChannelCount: number, workletRuntime?: AudioWorkletRuntime): WorkletNode;
    createWorkletProcessingNode(callback: (inputData: Array<Float32Array>, outputData: Array<Float32Array>, framesToProcess: number, currentTime: number) => void, workletRuntime?: AudioWorkletRuntime): WorkletProcessingNode;
    createWorkletSourceNode(callback: (audioData: Array<Float32Array>, framesToProcess: number, currentTime: number, startOffset: number) => void, workletRuntime?: AudioWorkletRuntime): WorkletSourceNode;
    createRecorderAdapter(): RecorderAdapterNode;
    createOscillator(): OscillatorNode;
    createStreamer(): StreamerNode;
    createConstantSource(): ConstantSourceNode;
    createGain(): GainNode;
    createDelay(maxDelayTime?: number): DelayNode;
    createStereoPanner(): StereoPannerNode;
    createBiquadFilter(): BiquadFilterNode;
    createIIRFilter(options: IIRFilterNodeOptions): IIRFilterNode;
    createBufferSource(options?: AudioBufferBaseSourceNodeOptions): AudioBufferSourceNode;
    createBufferQueueSource(options?: AudioBufferBaseSourceNodeOptions): AudioBufferQueueSourceNode;
    createBuffer(numOfChannels: number, length: number, sampleRate: number): AudioBuffer;
    createPeriodicWave(real: Float32Array, imag: Float32Array, constraints?: PeriodicWaveConstraints): PeriodicWave;
    createAnalyser(): AnalyserNode;
    createConvolver(options?: ConvolverNodeOptions): ConvolverNode;
    createWaveShaper(): WaveShaperNode;
}
//# sourceMappingURL=BaseAudioContext.d.ts.map